# C1. 
<p>
    Правильнее всего использовать медиану для описания типичной зарплаты во всех группах опыта.
    Дополнительно стоит указывать межквартильный размах или 25-й и 75-й перцентили, чтобы очертить диапазон, в котором лежит большинство предложений.
</p>

## Обоснование
<p> 
    Распределения зарплат во всех группах опыта скошены вправо. Что видно из расчётов в блоке B.
    <b>Из этого следует</b>, 
    <ol>
        <li> Основная масса вакансий сосредоточена на относительно низких зарплата </li>
        <li> небольшое количество вакансий с очень высокими зарплатами (правый хвост) </li>
        <li> высокие зарплаты — выбросы или редкие предложения. </li>
    </ol>
</p>
<p>
    Среднее — неудачный выбор метрики для данного распределения, потому что значения хвоста будут сильно искажать метрику, давая неверное представление о зарплатах.
    <b>Медиана</b> делит выборку на 2 равные части, она наилучший выбор, потому что:
    <ul>
        <li>Устойчива к выбросам, т.е не поменяет резко значение при появлении в данных аномалий</li>
        <li>Даже при сильной асимметрии медиана остаётся репрезентативной (отражает правдивое положение дел в выборке).</li>
    </ul>
</p>
<p>
    Прочие метрики. Не подходят из-за:
    <ol>
        <li>Мода: может быть не одна, плохо работает с непрерывными данными</li>
        <li>Усечённое среднее: cложнее интерпретировать</li>
        <li>Квартили: не дают одно число для типичной зарплаты</li>
    </ol>
</p>

# C2. 
<p><b>В данной ситуации нельзя верить заявленному утверждению.</b><p>

<p>
    Статья может давать искажённое представление о реальной зарплате:
</p>
<ol>
    <li>В анализе могли использовать неподходящие метрики, которые могут быть чувствительны к аномалиям(н-р, среднее).</li>
    <li>Нет представления о методологии анализа (происхождение датасета, предобработка)</li>
    <li>Какие факторы учитываются?</li>
</ol>

## Методологические оговорки

<p>
    Что подразумевается под средним? Например, как говорилось ранее, среднее будет неподходящей метрикой для наших данных, в частности.
    Как обрабатываются диапазоны зарплат? Предобработка данных? Актуальность собранных данных?
</p>

# C3

<h1>Проведём анализ</h1>

In [35]:
from  py.block_b import *

In [36]:
getStatisticsWithOutNaN(df_clean, 'От 1 года до 3 лет')

,Медиана,Среднее,Стандартное отклонение,25-й перцентиль,75-й перцентиль
0,147500.0,180820.886234,112001.85023,110000.0,207500.0

In [37]:
getStatisticsWithOutNaN(df_clean, 'От 3 до 6 лет')

,Медиана,Среднее,Стандартное отклонение,25-й перцентиль,75-й перцентиль
0,167500.0,175125.270982,67851.282088,125000.0,220000.0

<p>Для строгого утверждения проведём формальный статистический тест Манна-Уитни и рассчитаем p-value</p>

In [45]:
# Формируем выборки
group_1_3 = df_clean[df_clean['experience'] == 'От 1 года до 3 лет']['salary']
group_3_6 = df_clean[df_clean['experience'] == 'От 3 до 6 лет']['salary']

## Тест Манна-Уитни

In [50]:
import scipy.stats as stats

In [51]:
u_stat, p_value_mann = stats.mannwhitneyu(group_1_3, group_3_6, alternative='two-sided')

In [52]:
print(f"\nU-статистика: {u_stat:.1f}")
print(f"p-value: {p_value_mann:.6f}")

U-статистика: 284626873.0
p-value: 0.000000

In [53]:
alpha = 0.001
if p_value_mann < alpha:
    print(f"\nРазличие СТАТИСТИЧЕСКИ ЗНАЧИМО на уровне {alpha}")
    print(f"  Зарплаты в группе <От 3 до 6 лет> значимо выше, чем в <От 1 года до 3 лет>")
else:
    print(f"\nазличие НЕ значимо на уровне {alpha}")

Различие СТАТИСТИЧЕСКИ ЗНАЧИМО на уровне 0.001
  Зарплаты в группе <От 3 до 6 лет> значимо выше, чем в <От 1 года до 3 лет>

<p>
    Медианная разница в 20.000 и перекрытие 25/75 перцентилей 2-х групп, говорит об умеренном влиянии опыта на размер заработной платы.
    Веротяно, имеет место влияние географического фактора и др
</p>